CREATE TABLE IF NOT EXISTS balance(
    id INT NOT NULL AUTO_INCREMENT,
    atm_code VARCHAR(50) NOT NULL,
    balance DECIMAL (12,2) NULL DEFAULT '0.00',
    PRIMARY KEY (id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;